version: '3.9'
services:
  db:
    image: 'postgres:latest'
    container_name: database
    platform: linux/x86_64
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=planner
      - POSTGRES_USER=user
    ports:
      - '5432:5432'
    restart: 'always'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d projects -U user']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
